---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for a list of all hooks
repos:
  ### GENERAL ###
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-json
        exclude: ".devcontainer/devcontainer.json"
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      # TODO compare to 'thoughtworks/talisman', 'yelp/detect-secrets', 'githuardian/ggshield'
      - id: detect-private-key
      # - id: detect-aws-credentials
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: git-check # Configure in .gitattributes
      - id: script-must-have-extension
      - id: script-must-not-have-extension


default_language_version:
  python: python3
ci:
  autofix_commit_msg: |
    chore(pre-commit): auto fixes from hooks :rotating_light:

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: |
    chore(pre-commit): autoupdate :arrow_up:
exclude: ".idea"
