= CookieCutter Ansible Role
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://github.com/cruft/cruft[
Install Cruft] (e.g. using `pip3 install --user cruft`)
and issue the following command in the parent directory of this folder
to get started:

[subs="+quotes,attributes"]
----
user@machine:~/dev$ *cruft https://github.com/JonasPammer/cookiecutter-ansible-role.git*
----

== Features

=== General
* Includes the most Awesome README
+
[NOTE]
====
It is assumed that your project exists under https://app.fossa.com/projects[FOSSA.com].
====
* Includes Beginner-Friendly Development Documentation.
* Includes a
  https://code.visualstudio.com/docs/remote/containers[Visual Studio Code Development Container Definition].
* Includes a copy of the
  https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant Code of Conduct] as generated automatically by GitHub.
* Includes a Beginner-Friendly `CONTRIBUTING` file, inspired by
  https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md[Auth0's Open Source Template].
* Includes numerous https://pre-commit.com/[pre-commit] hooks to automatically
  find linting issues, format your files, and find common issues of version control and source code
* Includes a very much standard
  https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration[`yamllint` configuration]
  (enforced through pre-commit and checked by CI)
* Assumes enforcement of
  https://gist.github.com/JonasPammer/4ea577854ae10afe644bff366d7b2a8a[Conventional Commit]
  (checked by a pre-commit hook if activated)
+
[NOTE]
====
The resulting projects mentions that this is completely optional for casual contributors,
as *it is assumed that pull requests are squash-merged by maintainers*.
====
* Includes a basic `.gitignore` which includes exclusion rules for VisualStudioCode, JetBrains, VirtualEnv, Linux, Ansible, SVN, Windows and macOS

=== Ansible

* Includes all Files and Folders expected to be found in an Ansible Role.
* Every Ansible file starts with a conventional comment containing the name of the role and the purpose of the file
* Includes Ansible Galaxy `meta.yml`
* Includes Molecule Converge Definition with Docker and systemd-enabled Images
* Uses single `vars/main.yml` paradigm instead of per-distribution file and include tasks paradigm, as shown below:
+
[source,yaml]
----
_rolename_os_specific_var:app-name:
  Alpine: …
  Debian: …
  Debian_9: …

rolename_os_specific_var: "{{
  _rolename_packages[ansible_distribution ~'_'~ ansible_distribution_major_version]|default(
  rolename_packages[ansible_distribution] )|default(
  _rolename_packages[ansible_os_family] ) }}"
----

=== GitHub

[NOTE]
====
The resulting projects mentions that `pre-commit` installation is optional,
as it is assumed that the project is included in your `pre-commit.ci` account projects.
====

* Includes a `.gitattributes` file, ensuring LF line endings
* Includes GitHub *Issue Form Templates* for filing bug reports and feature requests using HTML forms
* Includes a GitHub *Pull Request Template*
* Includes a GitHub *Workflow to release to Ansible Galaxy*
+
[NOTE]
====
*Requires* a `GALAXY_API_KEY` secret present in the GitHub repository or organization!
====
* Includes a Continuous GitHub *Workflow to `yamllint` / `ansiblelint` all files*
* Includes a Continuous GitHub *Workflow to run `molecule` test's on a matrix of different OS's* (with systemd support)
* Includes a Continuous GitHub Workflow to *automatically stale/close issues and PRs* that have had no activity (updates or comments)
for 30/7 days respectively.
* Includes a GitHub Workflow to *declaratively manage labels*
** The predefined `labels.json` is inspired by the kubernetes project
* Includes a GitHub Workflow to denote size of pull requests by automagically labelling them
* Includes a
  https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates[Dependabot]
  configuration file to check for updates of used GitHub Actions themselves on a monthly basis