---
name: build self-contained READMEs

"on":
  push:

permissions:
  contents: read

# Cancel a currently running workflow from the same PR, branch or tag when a new workflow is triggered for it
concurrency:
  group: "{% raw %}${{ github.workflow }}{% endraw %}-{% raw %}${{ github.event.pull_request.number || github.ref }}{% endraw %}"
  cancel-in-progress: true

jobs:
  asciidoctor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      ### Setup
      - name: check out the codebase
        uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"

      - name: set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install asciidoctor and other relevant ruby gems
        run: gem install --no-document asciidoctor asciidoctor-reducer rouge coderay

      - name: get first line of commit message as variable
        shell: bash
        run: |
          echo "FIRST_LINE_OF_HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" | head -1 >> $GITHUB_ENV
        env:
          HEAD_COMMIT_MESSAGE: "{% raw %}${{ github.event.head_commit.message }}{% endraw %}"

      ### README.orig.adoc & co.
      - name: Generate README.adoc using ascidoctor-reducer.
        run: asciidoctor-reducer README.orig.adoc -o README.adoc

      - name: generate README.xml from README.adoc using ascidoctor
        run: asciidoctor -b docbook README.adoc

      - name: Generate README.md from README.xml using pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: "-f docbook -t markdown_strict README.xml -o README.md --wrap=none"

      ### SECURITY.adoc
      - name: generate SECURITY.xml from SECURITY.adoc using ascidoctor
        run: asciidoctor -b docbook SECURITY.adoc

      - name: Generate SECURITY.md from SECURITY.xml using pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: "-f docbook -t markdown_strict SECURITY.xml -o SECURITY.md --wrap=none"

      ### Commit
      - name: add 'changes will be lost' comment to generated files
        run: |
          sed -i \
          '1s|^|This file is being generated by .github/workflows/gh-pages.yml - all local changes will be lost eventually!\n|' \
          README.adoc README.md SECURITY.md

          sed -i '1s|\(.*\)|<!-- \1 -->|' README.md SECURITY.md
          sed -i '1s|\(.*\)|// \1|' README.adoc

      - id: is_renovate
        run: echo "is_renovate=$( [[ ${GITHUB_REF#refs/heads/} != renovate/* ]] && echo false || echo true )" >> $GITHUB_OUTPUT

      - name: Commit generated files.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "{% raw %}${{ env.FIRST_LINE_OF_HEAD_COMMIT_MESSAGE }}{% endraw %}\n{% raw %}${{ github.sha }}{% endraw %}"
          file_pattern: README.adoc README.md SECURITY.md
          disable_globbing: true
        if: steps.is_renovate.outputs.is_renovate == 'false'

      ### (Deploy README.adoc)
      - name: Generate HTML
        run: asciidoctor --backend=html5 --destination-dir docs --out-file index.html README.adoc
        if: github.ref == 'refs/heads/master'

      - name: upload docs directory for job transfer
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs
        if: github.ref == 'refs/heads/master'

  gh-pages:
    runs-on: ubuntu-latest
    needs: asciidoctor
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      pages: write
      id-token: write
      # delete-artifact@v4
      actions: write
    environment:
      name: github-pages
      url: "{% raw %}${{ steps.deployment.outputs.page_url }}{% endraw %}"
    steps:
      ### Deploy README.adoc
      - name: download docs directory from previous job
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: ./docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

      - name: docs artifact no longer needed
        uses: geekyeggo/delete-artifact@v4
        with:
          name: docs
          failOnError: false
