---
- name: DEBUG module variables ("vars")
  ansible.builtin.debug: msg="{% raw %}{{ vars | to_nice_yaml }}{% endraw %}"
  tags: vars

- name: DEBUG environment variables ("environment")
  ansible.builtin.debug: msg="{% raw %}{{ environment | to_nice_yaml }}{% endraw %}"
  tags: environment

- name: DEBUG host variables ("hostvars")
  ansible.builtin.debug: msg="{% raw %}{{ hostvars | to_nice_yaml }}{% endraw %}"
  tags: hostvars
