---
# tasks file for testing that variables of roles/{{ cookiecutter.role_name }} are set correctly

- name: test if variable_name is set correctly
  ansible.builtin.assert:
    that:
      - variable_name is defined
      - variable_name is number
      - variable_name >= 0
    quiet: yes
