= ansible-role-{{ cookiecutter.role_name }}
{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/ci.yml[image:https://github.com/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://app.fossa.com/projects/git%2Bgithub.com%2F{{ cookiecutter.github_user }}%2Fansible-role-{{ cookiecutter.role_name }}?ref=badge_shield[image:https://app.fossa.com/api/projects/git%2Bgithub.com%2F{{ cookiecutter.github_user }}%2Fansible-role-{{ cookiecutter.role_name }}.svg?type=small[FOSSA Licenses Status]]

// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}/master[image:https://results.pre-commit.ci/badge/github/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
https://open.vscode.dev/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]


ifdef::env-github[]
[TIP]
__A single-page version of this README can be found at https://{{ cookiecutter.github_user }}.github.io/ansible-role-{{ cookiecutter.role_name }}[
{{ cookiecutter.github_user }}.github.io/ansible-role-{{ cookiecutter.role_name }}].__
endif::[]


An Ansible role for {{ cookiecutter.project_short_purpose }}.


toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
{%- if cookiecutter.ansible_user_needs_to_become %}
The Ansible User needs to be able to `become`.
{% endif %}

The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
variable: default value
----
Description


[source,yaml]
----
variable: [OS-specific by default, see /vars directory]
----
Description


[source,yaml]
----
variable: [OS-specific by default, see /vars directory]
----
(Debian/Ubuntu only)
Description


[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

The machine needs to be prepared. In CI this is done using `molecule/default/prepare.yml`:

.link:molecule/default/prepare.yml[]
[source,yaml]
----
include::molecule/default/prepare.yml[]
----

Below you can find examples showcasing how this role may be used:

.Minimum Viable Play
====
[source,yaml]
----
roles:
    - "{{ cookiecutter.galaxy_name }}.{{ cookiecutter.role_name }}"

vars:
    some_var: "some_value"
----
====


[[development]]
== 📝 Development
include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/{{ cookiecutter.github_user }}/ansible-role-{{ cookiecutter.role_name }}/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-bootstrap/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----

https://app.fossa.com/projects/git%2Bgithub.com%2F{{ cookiecutter.github_user }}%2Fansible-role-{{ cookiecutter.role_name }}?ref=badge_large[image:https://app.fossa.com/api/projects/git%2Bgithub.com%2F{{ cookiecutter.github_user }}%2Fansible-role-{{ cookiecutter.role_name }}.svg?type=large[FOSSA Licensing Information]]
