---
# tasks file of ansible-role {{ cookiecutter.galaxy_name }}.{{ cookiecutter._role_name }}

- name: check if all variables have been set correctly
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost
