name: Test Jinja2
"on":
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "README.adoc"
      - "LICENSE"

jobs:
  test-latest:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: check out the codebase
        uses: actions/checkout@v2

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install latest cookiecutter from PyPI.
        run: pip3 install cookiecutter

      - name: Create from cookiecutter.
        run: cookiecutter . --output-dir ./out --no-input
