name: Test Jinja2
permissions: read-all
"on":
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "README.adoc"
      - "LICENSE"

jobs:
  test-latest:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: check out the codebase
        uses: actions/checkout@v3

      - name: set up python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: install development dependencies
        run: pip3 install -r requirements-dev.txt

      - name: Generate example project from cookiecutter.
        run: cookiecutter . --config-file .github/cookiecutter-example.yml --no-input

      - name: Run pre-commit on all files in generated directory.
        run: git init; git add .; pre-commit run --all-files
        working-directory: ./ansible-role-myrole
